package main

func main() {
	//RunTemplate()
	//RunStrategy()
	//RunState()
	//RunVisitor()
	//RunMemento()
	//RunCommand()
	//RunChainOfResponsibility()
	//RunIterator()
	//RunMediator()
	//RunProxy()
	RunFlyweight()
	//RunFacade()
	//RunDecorator()
	//RunComposite()
	//RunBuilder()
	//RunPrototype()
	//RunBridge()
	//RunAdapter()
	//RunAbstractFactory()
	//RunFactory()
	//RunSingletonThreadSafe2()
	//RunSingletonThreadSafe()
	//RunProducerConsumerWithBuffer()
	//RunObserverSubject()
}
